# Generated by Django 4.2.7 on 2023-12-03 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='name',
        ),
    ]
